#ifndef XYSYLIXOSINPUTMETHOD_GLOBAL_H
#define XYSYLIXOSINPUTMETHOD_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(XYSYLIXOSINPUTMETHOD_LIBRARY)
#  define XYSYLIXOSINPUTMETHODSHARED_EXPORT Q_DECL_EXPORT
#else
#  define XYSYLIXOSINPUTMETHODSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // XYSYLIXOSINPUTMETHOD_GLOBAL_H
